### ISSUE TITLE
No output files

### ISSUE THREAD

**Issue by maycaps** [hilts-vaughan/UnlinkMKV-GUI#14] opened 2016-05-23 14:06 UTC
So I've been trying to merge the seperate MKV files (openings & endings) of CoalGirls' Nisemonogatari batch. First of all, I have installed mkvtoolnix, strawberry perl and mono. I've tried both 32- and 64-bit versions of everything. So I put your unlinkmkv folder into my mkvtoolnix folder, ran the unlinkmkv as admin and tried to unlink my mkv-files. However, it's done within 10 seconds and there's no output files. Also it's unclear to me what I should download/use. I've tried this one [https://github.com/gnoling/UnlinkMKV](url), but also this one https://github.com/hilts-vaughan/UnlinkMKV-GUI/releases (lastest release). The first one crashed when I tried to unlink the files and the second one doesn't produce anything. 

I've got unlinkmkv to work in the past, so I don't know what I'm doing wrong this time. This was also done on a different computer. I hope you can help me with this.

**Comment by hilts-vaughan** [comment] 2016-05-23 16:30
Hi there,

Could we start with your operating system?

**Comment by maycaps** [comment] 2016-05-25 00:19
Hello,

I'm running on Windows 7 ultimate 64-bit OS. I've gotten unlinkmkv to run
now, but it still won't give any output files. The problem before was that
I did not installed the perl logging module (didn't read...). But now it
says that the files don't contain segmented chapters. Same goes for a
different batch of files regarding openings and endings of videos.

I hope you can help me with this.

2016-05-23 18:30 GMT+02:00 Vaughan Hilts notifications@github.com:

**Comment by hilts-vaughan** [comment] 2016-05-25 00:23
Hi there,

This is a known issue now; there was an update with the more recent versions of the tools. If you rollback to the 8.x series of MKVToolNix, it should work afaik. I'm hoping to put out a release this week or the next that will make it work with the 9.x series of MKVToolnix.

If you would like to help test the 9.x series patch, I ask you download the latest script @ https://raw.githubusercontent.com/hilts-vaughan/UnlinkMKV-GUI/bbb7e1af9ea39285371a963968a9cad54a977cbe/UnlinkMKV-GUI/UnlinkMKV-GUI/winport.pl

and then replace your winport.pl in your directory from the release you downloaded with that one, and try again. Keep in mind, this patch only works under OS X and Windows right now.

Otherwise, let me know what version of MKVToolNix you are running. 

Thanks!

**Comment by maycaps** [comment] 2016-05-25 00:49
Hello,

Thank you for your fast response. Sadly I still can't get it to work. I've
tried several older versions of mkvtoolnix, but it doesn't seem to make a
difference. I'm still getting the "no segmented chapters" message. I was
running on the latest 9.1.0 version of mkvtoolnix, then I downloaded the
8.0 and 8.9 versions. All had the same outcome. I'll wait for your next
update and hopefully I'll get it to work then!

Thank you for your response.

2016-05-25 2:23 GMT+02:00 Vaughan Hilts notifications@github.com:

**Comment by hilts-vaughan** [comment] 2016-05-25 00:52
Hi,

Could you send me an email (you can find it on my profile) with the release
/ file you are using?

I'll include it in the test cases before I release to make sure it works
for you.

Vaughan

**Comment by the1337moderator** [comment] 2016-05-25 01:07
maycaps,

Can you please open a command prompt and then call mkvinfo with the path to the mkv file as a parameter. `C:\Program Files (x86)\MKVToolNix\mkvinfo "C:\pathto\file.mkv"`. Please let us know if the output is generated in the command prompt window or if the mkvinfo window is opened with the output.

This may be a duplicate of a previous issue: [https://github.com/hilts-vaughan/UnlinkMKV-GUI/issues/13](https://github.com/hilts-vaughan/UnlinkMKV-GUI/issues/13)

**Comment by maycaps** [comment] 2016-05-25 01:23
Hello,

I'll try to do that tomorrow as it's getting pretty late over here. I might need some extra instructions how to do this as I am not really that computersmart, but I'll try to figure it out. I'll also read the thread you linked to in your mail, maybe it will be of some help.

Thank you for your time.

**Comment by hilts-vaughan** [comment] 2016-11-27 16:33
Since there has been no reply on this ticket in a few months, I'm closing it up. If you're still having issues, could you reopen another ticket and maybe try native backend mode, too?

**Closed as completed** 2016-11-27 16:33 UTC
