### ISSUE TITLE
Missing segments

### ISSUE THREAD

**Issue by Nutellaeis** [hilts-vaughan/UnlinkMKV-GUI#13] opened 2015-10-07 22:46 UTC
So it seems the tool does find out which files are missing but for some reason it can not find them. I have pasted a log here :
http://dpaste.com/063C85Q
but honestly it does not make much sense to me.

 If I run 
**mkvinfo "D:/Daten/Downloads/DomDom/Clannad/ed.mkv"**
it returns
**Segment-UID: 0x8e 0x31 0xeb 0x51 0xc6 0x08 0x7f 0x15 0xbf 0x09 0x09 0x59 0xe0 0x21 0x7f 0x9c**
which is reported as missing. Maybe I am just not seeing something really simple?

The release I am testing it on is a **[MII][SS-Eclipse][THORA]** release and I am running on **Windows 10 x64 professional**.

**Comment by hilts-vaughan** [comment] 2015-10-07 22:48
Sounds like a bug! I'll look into this and get back to you soon.

**Comment by Nutellaeis** [comment] 2015-10-14 11:23
Any news on this?

**Comment by the1337moderator** [comment] 2016-03-26 22:33
I receiving the same type of error. Below is the Output Log and a screenshot of mkvInfo:

```
UnlinkMKV
   removed tmp C:\Users\Owner\AppData\Local\Temp\1956
   created tmp C:\Users\Owner\AppData\Local\Temp\1956
   processing Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_01_(1280x720_Blu-ray_FLAC)_[C43B9D9D].mkv
      checking if file is segmented
         sys > mkvextract chapters "Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_01_(1280x720_Blu-ray_FLAC)_[C43B9D9D].mkv"
         "Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_01_(1280x720_Blu-ray_FLAC)_[C43B9D9D].mkv" contains segmented chapters
      generating chapter file
         loading chapters
            Checking for editions...
            Ordered flag found and dropped
            Done checking for editions...
            setting part [Coalgirls]_Nisemonogatari_01_(1280x720_Blu-ray_FLAC)_[C43B9D9D].mkv => Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_01_(1280x720_Blu-ray_FLAC)_[C43B9D9D].mkv
            Running on Windows; attempting to use symbolic link fallback for Windows
            sys > cmd /c mklink "C:\Users\Owner\AppData\Local\Temp\1956\parts\[Coalgirls]_Nisemonogatari_01_(1280x720_Blu-ray_FLAC)_[C43B9D9D].mkv" "Z:\monogatari\[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)\[Coalgirls]_Nisemonogatari_01_(1280x720_Blu-ray_FLAC)_[C43B9D9D].mkv"
            [INT]
    ChStart 00:00:0.000000001
    ChEnd   00:05:56.982000001
    Offset  00:00:00.000000000
    OffTE   00:05:56.982000001
            [EXT]
    ChStart 00:05:56.982000001
    ChEnd   00:07:27.030000002
    Offset  00:01:30.048000001
    OffTE   00:07:27.030000002
            setting part [Coalgirls]_Nisemonogatari_01_(1280x720_Blu-ray_FLAC)_[C43B9D9D].mkv => Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_01_(1280x720_Blu-ray_FLAC)_[C43B9D9D].mkv
            Running on Windows; attempting to use symbolic link fallback for Windows
            sys > cmd /c mklink "C:\Users\Owner\AppData\Local\Temp\1956\parts\[Coalgirls]_Nisemonogatari_01_(1280x720_Blu-ray_FLAC)_[C43B9D9D].mkv" "Z:\monogatari\[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)\[Coalgirls]_Nisemonogatari_01_(1280x720_Blu-ray_FLAC)_[C43B9D9D].mkv"
            [INT]
    ChStart 00:07:27.067000002
    ChEnd   00:24:10.073000002
    Offset  00:01:30.048000001
    OffTE   00:24:10.073000002
            [EXT]
    ChStart 00:24:10.073000002
    ChEnd   00:25:40.121000003
    Offset  00:03:0.096000002
    OffTE   00:25:40.121000003
            setting part [Coalgirls]_Nisemonogatari_01_(1280x720_Blu-ray_FLAC)_[C43B9D9D].mkv => Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_01_(1280x720_Blu-ray_FLAC)_[C43B9D9D].mkv
            Running on Windows; attempting to use symbolic link fallback for Windows
            sys > cmd /c mklink "C:\Users\Owner\AppData\Local\Temp\1956\parts\[Coalgirls]_Nisemonogatari_01_(1280x720_Blu-ray_FLAC)_[C43B9D9D].mkv" "Z:\monogatari\[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)\[Coalgirls]_Nisemonogatari_01_(1280x720_Blu-ray_FLAC)_[C43B9D9D].mkv"
            [INT]
    ChStart 00:25:40.155000003
    ChEnd   00:26:15.156000003
    Offset  00:03:0.096000002
    OffTE   00:26:15.156000003
         writing chapter temporary file
         looking for segment parts
            sys > mkvinfo "Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_02_(1280x720_Blu-ray_FLAC)_[164FBDC4].mkv"
            sys > mkvinfo "Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_03_(1280x720_Blu-ray_FLAC)_[17FA1D49].mkv"
            sys > mkvinfo "Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_04_(1280x720_Blu-ray_FLAC)_[7FA3F0BD].mkv"
            sys > mkvinfo "Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_05_(1280x720_Blu-ray_FLAC)_[EB868D50].mkv"
            sys > mkvinfo "Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_06_(1280x720_Blu-ray_FLAC)_[89FC4300].mkv"
            sys > mkvinfo "Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_07_(1280x720_Blu-ray_FLAC)_[24EC5245].mkv"
            sys > mkvinfo "Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_08_(1280x720_Blu-ray_FLAC)_[3B368DC3].mkv"
            sys > mkvinfo "Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_09_(1280x720_Blu-ray_FLAC)_[AB6BE020].mkv"
            sys > mkvinfo "Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_10_(1280x720_Blu-ray_FLAC)_[631AE5D8].mkv"
            sys > mkvinfo "Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_11_(1280x720_Blu-ray_FLAC)_[39FEAA52].mkv"
            sys > mkvinfo "Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_ED1_(1280x720_Blu-ray_FLAC)_[80A0E215].mkv"
            sys > mkvinfo "Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_ED2_(1280x720_Blu-ray_FLAC)_[B021ED05].mkv"
            sys > mkvinfo "Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_ED3_(1280x720_Blu-ray_FLAC)_[6C0FC6CF].mkv"
            sys > mkvinfo "Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_OP1a_(1280x720_Blu-ray_FLAC)_[6D5C867B].mkv"
            sys > mkvinfo "Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_OP1b_(1280x720_Blu-ray_FLAC)_[EDABECD5].mkv"
            sys > mkvinfo "Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_OP2_(1280x720_Blu-ray_FLAC)_[C1F2ACDB].mkv"
            sys > mkvinfo "Z:/monogatari/[Coalgirls]_Nisemonogatari_(1280x720_Blu-ray_FLAC)/[Coalgirls]_Nisemonogatari_OP3_(1280x720_Blu-ray_FLAC)_[0F161B82].mkv"
         checking that all required segments were found
         missing segment: 0x88 0x79 0x26 0x47 0x4c 0x7d 0x6a 0x4a 0x98 0x4d 0x93 0x8a 0xe8 0xe0 0x11 0x92
         missing segment: 0xb4 0x6d 0x8b 0x99 0xe1 0x6b 0x17 0x36 0xae 0xe4 0x12 0x1f 0x8a 0x34 0x82 0x79
         missing segments!
         removed tmp C:\Users\Owner\AppData\Local\Temp\1956 [exiting]
```

![image](https://cloud.githubusercontent.com/assets/7213142/14062769/357589fe-f379-11e5-9873-ab8c44acba3b.png)

**Comment by Hisucchi** [comment] 2016-04-06 18:23
Same issue with Eden of the East, gg-Thora. For purposes of logging, I had with one episode+op+ed in the folder, because it would just reopen mkvinfo for every file in the folder.

Same OS as OP by the way, Win10 x64 Pro. Might that be the issue?

> UnlinkMKV
>    removed tmp C:\Users\redacted\AppData\Local\Temp\9920
>    created tmp C:\Users\redacted\AppData\Local\Temp\9920
>    processing D:/redacted/Desktop/backup/Eden_of_the_East_ED_[1080p,BluRay,x264]_-_gg-THORA.mkv
>       checking if file is segmented
>          sys > mkvextract chapters "D:/redacted/Desktop/backup/Eden_of_the_East_ED_[1080p,BluRay,x264]_-_gg-THORA.mkv"
>          "D:/redacted/Desktop/backup/Eden_of_the_East_ED_[1080p,BluRay,x264]_-_gg-THORA.mkv" does not contain segmented chapters
>       removed tmp C:\Users\redacted\AppData\Local\Temp\9920
>       created tmp C:\Users\redacted\AppData\Local\Temp\9920
>    removed tmp C:\Users\redacted\AppData\Local\Temp\9920 [exiting]
> UnlinkMKV
>    removed tmp C:\Users\redacted\AppData\Local\Temp\12076
>    created tmp C:\Users\redacted\AppData\Local\Temp\12076
>    processing D:/redacted/Desktop/backup/Eden_of_the_East_Ep04_Real_Reality_Fictional_Reality_[1080p,BluRay,x264]_-_gg-THORA.mkv
>       checking if file is segmented
>          sys > mkvextract chapters "D:/redacted/Desktop/backup/Eden_of_the_East_Ep04_Real_Reality_Fictional_Reality_[1080p,BluRay,x264]_-_gg-THORA.mkv"
>          "D:/redacted/Desktop/backup/Eden_of_the_East_Ep04_Real_Reality_Fictional_Reality_[1080p,BluRay,x264]_-_gg-THORA.mkv" contains segmented chapters
>       generating chapter file
>          loading chapters
>             Checking for editions...
>             Ordered flag found and dropped
>             Done checking for editions...
>             [EXT]
>   ChStart 00:00:00.000000000
>   ChEnd   00:01:21.088000001
>   Offset  00:01:21.088000001
>   OffTE   00:01:21.088000001
>             setting part Eden_of_the_East_Ep04_Real_Reality_Fictional_Reality_[1080p,BluRay,x264]_-_gg-THORA.mkv => D:/redacted/Desktop/backup/Eden_of_the_East_Ep04_Real_Reality_Fictional_Reality_[1080p,BluRay,x264]_-_gg-THORA.mkv
>             Running on Windows; attempting to use symbolic link fallback for Windows
>             sys > cmd /c mklink "C:\Users\redacted\AppData\Local\Temp\12076\parts\Eden_of_the_East_Ep04_Real_Reality_Fictional_Reality_[1080p,BluRay,x264]_-_gg-THORA.mkv" "D:\redacted\Desktop\backup\Eden_of_the_East_Ep04_Real_Reality_Fictional_Reality_[1080p,BluRay,x264]_-_gg-THORA.mkv"
>             [INT]
>   ChStart 00:01:21.088000002
>   ChEnd   00:21:12.277000002
>   Offset  00:01:21.088000001
>   OffTE   00:21:12.277000002
>             [EXT]
>   ChStart 00:21:12.277000002
>   ChEnd   00:22:33.365000003
>   Offset  00:02:42.176000002
>   OffTE   00:22:33.365000003
>          writing chapter temporary file
>          looking for segment parts
>             sys > mkvinfo "D:/redacted/Desktop/backup/Eden_of_the_East_ED_[1080p,BluRay,x264]_-_gg-THORA.mkv"
>             sys > mkvinfo "D:/redacted/Desktop/backup/Eden_of_the_East_OP_[1080p,BluRay,x264]_-_gg-THORA.mkv"
>          checking that all required segments were found
>          missing segment: 0xa0 0x36 0xdf 0x78 0x7f 0xec 0xc5 0x9f 0x8b 0x55 0x98 0xc6 0xa2 0xb3 0x0f 0xcb
>          missing segment: 0xbf 0x12 0x67 0xab 0xf8 0x93 0xdf 0x81 0x9f 0x16 0xd1 0x56 0xd0 0xc4 0xaf 0xbd
>          missing segments!
>          removed tmp C:\Users\redacted\AppData\Local\Temp\12076 [exiting]
> UnlinkMKV
>    removed tmp C:\Users\redacted\AppData\Local\Temp\13028
>    created tmp C:\Users\redacted\AppData\Local\Temp\13028
>    processing D:/redacted/Desktop/backup/Eden_of_the_East_OP_[1080p,BluRay,x264]_-_gg-THORA.mkv
>       checking if file is segmented
>          sys > mkvextract chapters "D:/redacted/Desktop/backup/Eden_of_the_East_OP_[1080p,BluRay,x264]_-_gg-THORA.mkv"
>          "D:/redacted/Desktop/backup/Eden_of_the_East_OP_[1080p,BluRay,x264]_-_gg-THORA.mkv" does not contain segmented chapters
>       removed tmp C:\Users\redacted\AppData\Local\Temp\13028
>       created tmp C:\Users\redacted\AppData\Local\Temp\13028
>    removed tmp C:\Users\redacted\AppData\Local\Temp\13028 [exiting]

**Comment by hilts-vaughan** [comment] 2016-04-06 18:24
Since there's so many of you at this point, I'm going to make this my top
priority after the weekend. I didn't know so many people were using this
still. :)

**Comment by Hisucchi** [comment] 2016-04-06 18:28
Thanks for the quick reply! :) Yeah just bumped into your tool, couldn't really find a solution to getting ordered chapters to run through UMS other than unlinking the files.

**Comment by the1337moderator** [comment] 2016-04-06 19:56
If you could assist me in understanding Perl, I can do my best to help in resolving this issue. I am quite proficient in VB.NET. I can read and understand C# .NET, but have minimal experience. Not sure if you want mixed code in your project though.

**Comment by hilts-vaughan** [comment] 2016-04-06 20:01
The issue is certainly in Perl land -- I'd like to port it to native C# at
some point, though.

Mixed code is fine -- I welcome pull requests and people have contributed
before.

**Comment by the1337moderator** [comment] 2016-04-06 20:08
I'll start working on porting the Perl script over to .NET then, but not sure how far I'll get with it.

**Comment by the1337moderator** [comment] 2016-04-17 08:28
Maybe I found the problem? When perl executes this line: `my ($id, $dur) = $self->mkvinfo("\"$mkv\"");`  on line 301, the mkvinfo() function is called with the path of mkv file. Then on line 777 the sys() function , `$self->sys($self->{opt}->{mkvinfo}, $file))`, is called, The value of `{mkvinfo}` is simply `'mkvinfo'` (line 46) and on line 815, `$app` is set to the value of `'mkvinfo'` and on line 817 `$cmd` is set to `'$app @_'` which at runtime will be `mkvinfo volume:/path/to/file.mkv`.

If you call mkvinfo from the command line in windows without any options, nothing is outputted to the console; the gui is opened and the command prompt waits for mkvinfo window to be closed. I confirmed this on Windows 10 with MKVToolNIX 64-bit and 32-bit.  I believe that mkvinfo needs to be called with the -G or --no-gui argument so that the output will be put in the console of the cmd prompt. With the -r option combined with -G, the output can then be sent to a file.

Just something I came across when documenting the Perl script and trying to figure out what line 779 was doing.

**Comment by hilts-vaughan** [comment] 2016-04-21 18:40
Looks like that's an issue in some cases, indeed!

**Comment by dawastl** [comment] 2016-07-13 10:37
I had the same issue as Maximilian-N. I realized that he also had a German language Windows. 

Mkvtoolnix comes with different locales and uses the German locale on my system. I deleted the locale folder in the mkvtoolnix folder and voila, unlinkmkv suddenly had no problems finding the right segments.

I guess unlinkmkv requires an English mkvinfo output to parse.

**Comment by Shadowghost** [comment] 2016-07-23 21:30
@dawastl thanks for the tip, that helped me a lot, I also struggled with missing segments. You should file a bug report at the main UnlinkMKV repo too.

**Comment by hilts-vaughan** [comment] 2016-11-17 03:10
It would appear this issue should be resoled now. I left a note in the README about system locales and newer versions no longer should spawn the GUI.

**Closed as completed by hilts-vaughan** 2016-11-17 03:10 UTC
